### ISSUE TITLE
Unexpected kwargs: {'itllava_vit_r': 92}

### ISSUE THREAD

**Issue by Cola-any** [hulianyuyy/iLLaVA#2]
Hi, thanks for sharing your project. 
When I evaluate the video benchmark following [this](https://github.com/hulianyuyy/iLLaVA?tab=readme-ov-file#video-benchmarks), I get the error below. Can you help me?

```
Traceback (most recent call last):
  File "/home/user/MLLM/iLLaVA/src/lmms_eval-0.2.4/lmms_eval/__main__.py", line 329, in cli_evaluate
    results, samples = cli_evaluate_single(args)
  File "/home/user/MLLM/iLLaVA/src/lmms_eval-0.2.4/lmms_eval/__main__.py", line 470, in cli_evaluate_single
    results = evaluator.simple_evaluate(
  File "/home/user/MLLM/iLLaVA/src/lmms_eval-0.2.4/lmms_eval/utils.py", line 533, in _wrapper
    return fn(*args, **kwargs)
  File "/home/user/MLLM/iLLaVA/src/lmms_eval-0.2.4/lmms_eval/evaluator.py", line 169, in simple_evaluate
    lm = ModelClass.create_from_arg_string(
  File "/home/user/MLLM/iLLaVA/src/lmms_eval-0.2.4/lmms_eval/api/model.py", line 110, in create_from_arg_string
    return cls(**args, **args2)
  File "/home/user/MLLM/iLLaVA/src/lmms_eval-0.2.4/lmms_eval/models/llava_onevision_training_free.py", line 102, in __init__
    assert kwargs == {}, f"Unexpected kwargs: {kwargs}"
AssertionError: Unexpected kwargs: {'itllava_vit_r': 92}
2024-12-20 11:19:36.755 | ERROR    | lmms_eval.__main__:cli_evaluate:348 - Error during evaluation: Unexpected kwargs: {'itllava_vit_r': 92}. Please set `--verbosity=DEBUG` to get more information.
```

**Comment by Cola-any** [comment]
Well, I find that the command [here](https://github.com/hulianyuyy/iLLaVA?tab=readme-ov-file#video-benchmarks) mistakenly wrote `illava_vit_r` as `itllava_vit_r`.

**Comment by hulianyuyy** [comment]
Thanks, i have corrected it.
